plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-parcelize'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "dev.dmayr.taptovibrate"
        minSdkVersion 19
        //noinspection OldTargetApi
        targetSdk 34
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    buildFeatures {
        viewBinding = true
    }

    namespace = "dev.dmayr.taptovibrate"
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {

    //noinspection GradleDependency
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$version_kotlin"
    //noinspection GradleDependency
    implementation "androidx.core:core-ktx:$version_core"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$version_lifecycle"
    implementation "androidx.constraintlayout:constraintlayout:$version_constraint_layout"
    //noinspection GradleDependency
    implementation "androidx.appcompat:appcompat:$version_appcompat"
    implementation "com.google.android.material:material:$version_material"
    implementation "com.jakewharton.timber:timber:$version_timber"
    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test.ext:junit:1.2.1"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.6.1"
}
